services:
  osrm-backend:
    image: ghcr.io/project-osrm/osrm-backend
    tty: true
    stdin_open: true
    ports:
      - 8080:5000
    volumes:
      - ./osrm-data:/data
    command: >
      bash -c "
      apt update -y && upgrade -y;
      apt install wget -y;

      if [ ! -f /data/map.osm.pbf ]; then
        echo 'Downloading OSM data...';
        wget -O /data/map.osm.pbf https://download.geofabrik.de/asia/thailand-latest.osm.pbf;
      fi

      if [ ! -f /data/car.lua ]; then
        echo 'Downloading car.lua profile...';
        wget -O /data/car.lua https://raw.githubusercontent.com/Project-OSRM/osrm-backend/master/profiles/car.lua;
      fi

      if [ ! -f /data/map.osrm ]; then
        echo 'Extracting OSM data...';
        osrm-extract -p /data/car.lua /data/map.osm.pbf;
        echo 'Partitioning OSRM data...';
        osrm-partition /data/map.osrm;
        echo 'Contracting OSRM data...';
        osrm-customize /data/map.osrm;
      fi

      echo 'Starting OSRM routing server...';
      osrm-routed --algorithm mld /data/map.osrm
      "
