import type { Metadata } from "next";
import "bulma/css/bulma.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ width: "100%", height: "100%" }}>
        {children}
      </body>
    </html>
  );
}
